### ISSUE TITLE
linux-rga not found

### ISSUE THREAD

**Issue by Prime9999** [EmuELEC/EmuELEC#315] opened 2020-10-04 01:14 UTC
I checkouted EmuELEC-aarch64 to build EmuElec for Odroid Go Advance.
But while building, the following error is displayed.

```
$ LANG=C PROJECT=Rockchip DEVICE=OdroidGoAdvance ARCH=aarch64 DISTRO=EmuELEC make image
./scripts/image mkimage

 =================================================================================
 Configuration for EmuELEC (community)
 =================================================================================

 Buildoptions:
 ======================================================
 - CPU (ARCH):                           cortex-a35 (aarch64)
 - FLOAT:                                hard
 - FPU:                                  fp-armv8
 - CPU features:                         64bit neon
 - LTO (Link Time Optimization) support: yes
 - GOLD (Google Linker) Support:         yes
 - LLVM support:                         no
 - DEBUG:                                no

 Graphic configuration:
 ======================================================
 - OpenGL (GLX) support (provider):      no (no)
 - OpenGLES support (provider):          yes (mali-bifrost)
 - uvesafb support:                      no

 Hardware decoder configuration:
 ======================================================
 - Kodi Player driver:                   libmali
 - VAAPI Support:                        no
 - VDPAU Support:                        no

 Input device configuration:
 ======================================================
 - Remote support:                       no
 - CEC Adapter support:                  no
 - CEC Framework support:                no
 - Kodi Joystick support:                yes

 Misc. hardware configuration:
 ======================================================
 - ALSA support:                         yes
 - Pulseaudio support:                   yes
 - Bluetooth support:                    no
 - Include driver:                       RTL8812AU
 - Include firmware:                     wlan-firmware
 - Include firmware:                     misc-firmware

 Network service configuration:
 ======================================================
 - Avahi (Zeroconf) support:             no
 - NFS mounting support:                 no
 - SAMBA mounting support:               yes
 - SAMBA server support:                 yes
 - SFTP server support:                  yes
 - OpenVPN support:                      no
 - WireGuard support:                    yes

 OS configuration:
 ======================================================
 - OEM Support:                          yes
 - Default ROOT Password:                emuelec
 - Bootloader:                           u-boot
 - UDevil support:                       yes
 - Installer support:                    no
 - Include package:                      dtc

 Misc. Filesystems:
 ======================================================
 - Swap Support:                         yes
   - Swapfile default size:              128
 - exFAT Support (via Fuse):             yes
 - NTFS Support (via Fuse):              yes
 - Install HFS Tools:                    yes

 =================================================================================
 End Configuration for EmuELEC
 =================================================================================



Packages loaded : 1145
Build trigger(s): 1 [image]
Package steps   : 378

[002/378] [DONE] build   xz:host
[001/378] [DONE] build   sed:host
[004/378] [DONE] build   gettext:host
[003/378] [DONE] build   ccache:host
[005/378] [DONE] build   libtool:host
[007/378] [DONE] build   pkg-config:host
[008/378] [DONE] build   autoconf:host
[009/378] [DONE] build   automake:host
[011/378] [DONE] build   intltool:host
[006/378] [DONE] build   configtools:host
[010/378] [DONE] build   make:host
[012/378] [DONE] build   m4:host
[013/378] [DONE] build   autoconf-archive:host
[014/378] [DONE] build   bison:host
[015/378] [DONE] build   autotools:host
[016/378] [DONE] build   openssl:host
[017/378] [DONE] build   flex:host
[018/378] [DONE] build   binutils:host
[020/378] [DONE] build   gmp:host
[019/378] [DONE] build   mpc:host
[022/378] [DONE] build   mpfr:host
[023/378] [DONE] build   pigz:host
[021/378] [DONE] build   cmake:host
[024/378] [DONE] build   zlib:host
[025/378] [DONE] build   linux:host
[026/378] [DONE] build   libxml2:host
[027/378] [DONE] build   gcc:host
INSTALL      gcc (bootstrap)
[028/378] [DONE] install gcc:bootstrap
[029/378] [DONE] build   libxslt:host
[030/378] [DONE] build   p7zip:host
[031/378] [DONE] build   bzip2:host
[032/378] [DONE] build   sqlite:host
[033/378] [DONE] build   xmlstarlet:host
[034/378] [DONE] build   Python2:host
[035/378] [DONE] build   libffi:host
[036/378] [DONE] build   ninja:host
[038/378] [DONE] build   util-linux:host
[037/378] [DONE] build   zstd:host
[039/378] [DONE] build   Python3:host
[040/378] [DONE] build   pathlib:host
[041/378] [DONE] build   setuptools:host
[042/378] [DONE] build   meson:host
[043/378] [DONE] build   lzo:host
[044/378] [DONE] build   kmod:host
[045/378] [DONE] build   dosfstools:host
[046/378] [DONE] build   mtools:host
[050/378] [DONE] build   squashfs:host
[048/378] [DONE] build   e2fsprogs:host
[049/378] [DONE] build   populatefs:host
[051/378] [DONE] build   libcap:host
[047/378] [DONE] build   fakeroot:host
[052/378] [DONE] build   elfutils:host
[053/378] [DONE] build   cpio:host
INSTALL      wireless-regdb (target)
[054/378] [DONE] install wireless-regdb
INSTALL      gcc (host)
INSTALL      gcc (target)
[055/378] [DONE] install gcc
INSTALL      libunwind (target)
[056/378] [DONE] install libunwind
INSTALL      ccache (host)
INSTALL      autotools (host)
INSTALL      linux (host)
INSTALL      pigz (host)
INSTALL      glibc (target)
[057/378] [DONE] install glibc
INSTALL      configtools (host)
INSTALL      make (host)
INSTALL      xz (host)
INSTALL      sed (host)
INSTALL      pkg-config (host)
INSTALL      autoconf (host)
INSTALL      automake (host)
INSTALL      intltool (host)
INSTALL      libtool (host)
INSTALL      autoconf-archive (host)
INSTALL      bison (host)
INSTALL      flex (host)
INSTALL      cmake (host)
INSTALL      xmlstarlet (host)
INSTALL      p7zip (host)
INSTALL      ninja (host)
INSTALL      meson (host)
INSTALL      toolchain (target)
[058/378] [DONE] install toolchain
INSTALL      keyutils (target)
[062/378] [DONE] install keyutils
INSTALL      tz (target)
[059/378] [DONE] install tz
INSTALL      libidn2 (target)
[060/378] [DONE] install libidn2
INSTALL      openssl (target)
[063/378] [DONE] install openssl
INSTALL      zlib (target)
[064/378] [DONE] install zlib
INSTALL      driverselect (target)
[061/378] [DONE] install driverselect
[065/378] [DONE] build   swig:host
INSTALL      elfutils (host)
INSTALL      elfutils (target)
[066/378] [DONE] install elfutils
INSTALL      kernel-firmware (target)
[067/378] [DONE] install kernel-firmware
INSTALL      binutils (host)
INSTALL      binutils (target)
[068/378] [DONE] install binutils
INSTALL      libc (target)
[069/378] [DONE] install libc
INSTALL      rfkill (target)
[070/378] [DONE] install rfkill
INSTALL      rkbin (target)
[071/378] [DONE] install rkbin
[072/378] [DONE] build   busybox:host
INSTALL      wlan-firmware (target)
[073/378] [DONE] install wlan-firmware
INSTALL      misc-firmware (target)
[074/378] [DONE] install misc-firmware
INSTALL      hdparm (target)
[075/378] [DONE] install hdparm
INSTALL      linux-firmware (target)
[076/378] [DONE] install linux-firmware
INSTALL      hd-idle (target)
[077/378] [DONE] install hd-idle
INSTALL      dosfstools (target)
[078/378] [DONE] install dosfstools
INSTALL      swig (host)
INSTALL      u-boot (target)
[079/378] [DONE] install u-boot
INSTALL      bzip2 (target)
[080/378] [DONE] install bzip2
INSTALL      diskdev_cmds (target)
[081/378] [DONE] install diskdev_cmds
INSTALL      zip (target)
[082/378] [DONE] install zip
INSTALL      e2fsprogs (target)
[083/378] [DONE] install e2fsprogs
INSTALL      cpio (host)
INSTALL      kmod (host)
INSTALL      linux (target)
[084/378] [DONE] install linux
INSTALL      unzip (target)
[085/378] [DONE] install unzip
INSTALL      libcap (target)
[086/378] [DONE] install libcap
INSTALL      util-linux (target)
[087/378] [DONE] install util-linux
INSTALL      kmod (target)
[088/378] [DONE] install kmod
INSTALL      RTL8812AU (target)
[089/378] [DONE] install RTL8812AU
[090/378] [DONE] build   parted:host
INSTALL      entropy (target)
[091/378] [DONE] install entropy
INSTALL      wait-time-sync (target)
[092/378] [DONE] install wait-time-sync
[093/378] [DONE] build   ncurses:host
INSTALL      linux-drivers (target)
[094/378] [DONE] install linux-drivers
INSTALL      popt (target)
[095/378] [DONE] install popt
INSTALL      crossguid (target)
[096/378] [DONE] install crossguid
INSTALL      libtirpc (target)
[097/378] [DONE] install libtirpc
INSTALL      parted (host)
INSTALL      parted (target)
[098/378] [DONE] install parted
INSTALL      ncurses (host)
INSTALL      ncurses (target)
[099/378] [DONE] install ncurses
INSTALL      systemd (target)
[100/378] [DONE] install systemd
INSTALL      gptfdisk (target)
[101/378] [DONE] install gptfdisk
INSTALL      procps-ng (target)
[102/378] [DONE] install procps-ng
INSTALL      nano (target)
[103/378] [DONE] install nano
INSTALL      libusb (target)
[104/378] [DONE] install libusb
INSTALL      pcre (target)
[105/378] [DONE] install pcre
INSTALL      util-macros (target)
[106/378] [DONE] install util-macros
INSTALL      liberation-fonts-ttf (target)
[107/378] [DONE] install liberation-fonts-ttf
INSTALL      libffi (target)
[108/378] [DONE] install libffi
INSTALL      usbutils (target)
[109/378] [DONE] install usbutils
INSTALL      expat (target)
[110/378] [DONE] install expat
INSTALL      corefonts (target)
[111/378] [DONE] install corefonts
INSTALL      libmnl (target)
[112/378] [DONE] install libmnl
INSTALL      readline (target)
[113/378] [DONE] install readline
INSTALL      libnftnl (target)
[114/378] [DONE] install libnftnl
INSTALL      dbus (target)
[115/378] [DONE] install dbus
INSTALL      libnl (target)
[116/378] [DONE] install libnl
INSTALL      Python3 (host)
INSTALL      glib (target)
[117/378] [DONE] install glib
INSTALL      netbase (target)
[118/378] [DONE] install netbase
INSTALL      ethtool (target)
[119/378] [DONE] install ethtool
INSTALL      wpa_supplicant (target)
[120/378] [DONE] install wpa_supplicant
INSTALL      iptables (target)
[121/378] [DONE] install iptables
INSTALL      attr (target)
[122/378] [DONE] install attr
INSTALL      openssh (target)
[123/378] [DONE] install openssh
INSTALL      iw (target)
[124/378] [DONE] install iw
INSTALL      rsync (target)
[125/378] [DONE] install rsync
INSTALL      busybox (host)
INSTALL      busybox (target)
[126/378] [DONE] install busybox
INSTALL      libaio (target)
[127/378] [DONE] install libaio
INSTALL      connman (target)
[128/378] [DONE] install connman
INSTALL      sqlite (target)
[129/378] [DONE] install sqlite
INSTALL      dtc (target)
[130/378] [DONE] install dtc
INSTALL      wireguard-tools (target)
[131/378] [DONE] install wireguard-tools
INSTALL      wireguard-linux-compat (target)
[132/378] [DONE] install wireguard-linux-compat
INSTALL      misc-packages (target)
[135/378] [DONE] install misc-packages
INSTALL      memtester (target)
[133/378] [DONE] install memtester
INSTALL      edid-decode (target)
[134/378] [DONE] install edid-decode
INSTALL      gdb (target)
[136/378] [DONE] install gdb
INSTALL      alsa-lib (target)
[137/378] [DONE] install alsa-lib
INSTALL      debug (target)
[138/378] [DONE] install debug
INSTALL      fuse (target)
[139/378] [DONE] install fuse
INSTALL      alsa-utils (target)
[140/378] [DONE] install alsa-utils
INSTALL      libgpg-error (target)
[141/378] [DONE] install libgpg-error
INSTALL      udevil (target)
[142/378] [DONE] install udevil
INSTALL      Python2 (host)
INSTALL      Python2 (target)
[143/378] [DONE] install Python2
INSTALL      fuse-exfat (target)
[144/378] [DONE] install fuse-exfat
INSTALL      alsa (target)
[145/378] [DONE] install alsa
INSTALL      libpciaccess (target)
[146/378] [DONE] install libpciaccess
INSTALL      soxr (target)
[147/378] [DONE] install soxr
INSTALL      libdrm (target)
[148/378] [DONE] install libdrm
GET      librga (archive)
--2020-10-04 10:03:46--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:46 ERROR 404: Not Found.

--2020-10-04 10:03:46--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:46--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:48 ERROR 404: Not Found.

--2020-10-04 10:03:48--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 13.114.40.48
Connecting to github.com (github.com)|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:48 ERROR 404: Not Found.

--2020-10-04 10:03:48--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:48--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:49 ERROR 404: Not Found.

--2020-10-04 10:03:49--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:49 ERROR 404: Not Found.

--2020-10-04 10:03:49--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:50--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:51 ERROR 404: Not Found.

--2020-10-04 10:03:51--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 13.114.40.48
Connecting to github.com (github.com)|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:51 ERROR 404: Not Found.

--2020-10-04 10:03:52--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:52--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:53 ERROR 404: Not Found.

--2020-10-04 10:03:53--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:53 ERROR 404: Not Found.

--2020-10-04 10:03:53--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:54--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:55 ERROR 404: Not Found.

--2020-10-04 10:03:55--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:55 ERROR 404: Not Found.

--2020-10-04 10:03:55--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:56--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:57 ERROR 404: Not Found.

--2020-10-04 10:03:57--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 13.114.40.48
Connecting to github.com (github.com)|13.114.40.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:57 ERROR 404: Not Found.

--2020-10-04 10:03:57--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:58--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:59 ERROR 404: Not Found.

--2020-10-04 10:03:59--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:03:59 ERROR 404: Not Found.

--2020-10-04 10:03:59--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:03:59--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:04:01 ERROR 404: Not Found.

--2020-10-04 10:04:01--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.69.186.44
Connecting to github.com (github.com)|52.69.186.44|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:04:01 ERROR 404: Not Found.

--2020-10-04 10:04:01--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:04:01--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:04:02 ERROR 404: Not Found.

--2020-10-04 10:04:02--  https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving github.com (github.com)... 52.192.72.89
Connecting to github.com (github.com)|52.192.72.89|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:04:02 ERROR 404: Not Found.

--2020-10-04 10:04:02--  http://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Resolving sources.libreelec.tv (sources.libreelec.tv)... 138.68.75.163
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz [following]
--2020-10-04 10:04:03--  https://sources.libreelec.tv/mirror/librga/librga-72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Connecting to sources.libreelec.tv (sources.libreelec.tv)|138.68.75.163|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-04 10:04:04 ERROR 404: Not Found.


Cannot get librga sources : https://github.com/rockchip-linux/linux-rga/archive/72e7764a9fe358e6ad50eb1b21176cc95802c7fb.tar.gz
Try later!
FAILURE: scripts/install librga has failed!
[149/378] [FAIL] install librga

The following logs for this failure are available:
  stdout: /home/imai/work/EmuElec/EmuELEC/build.EmuELEC-OdroidGoAdvance.aarch64-3.6/.threads/logs/159/stdout
  stderr: /home/imai/work/EmuElec/EmuELEC/build.EmuELEC-OdroidGoAdvance.aarch64-3.6/.threads/logs/159/stderr

parallel: This job failed:
package_worker 1 159 378 'install librga'
Parallel build failure - see log for details. Time of failure: Sun Oct  4 10:04:05 JST 2020
make: *** [Makefile:12: image] Error 1
$
```

**Comment by shantigilbert** [comment] 2020-10-04 01:55
Duplicate of #301

**Closed** 2020-10-04 01:55 UTC
