### ISSUE TITLE
720p resolution error on S905w after 4.5 clean install

### ISSUE THREAD

**Issue by marcus-abreu** [EmuELEC/EmuELEC#900] opened 2022-04-20 12:04 UTC
My S905w (tx3 mini) worked fine with 720p resolution until yesterday, when I did a clean install to 4.5 version. I just can't change the resolution to 720p without glitches.
Thanks.

**Comment by Langerz82** [comment] 2022-04-22 02:37
What glitches do you mean exactly? Is it a video change warning comes up? You can override it by just selecting yes.

**Comment by marcus-abreu** [comment] 2022-04-22 21:24
Thanks for the reply. It´s hard to describe, so I took some snapshots:
![20220422_131606](https://user-images.githubusercontent.com/21199224/164796276-f16f1ead-3a49-43a7-8053-bd33ed7b7ed3.jpg)
It happens after reboot the system.

**Comment by AlienatedDiego** [comment] 2022-04-22 23:39
it is correct, 720p is broken in 4.5 for Amlogic old(s905w) devices

**Comment by Langerz82** [comment] 2022-04-23 02:23
That looks like your resolution setting is not matching the emulationstation resolution setting. Make sure emulationstation resolution matches the output.
If you have a resolution set in: /flash/config.ini look for the key hdmimode and make sure it's commented out (prefix it with a #). You may have to remount the flash directory to make changes by doing:
```
mount -o rw,remount /flash
```

Also make sure there is no file: /storage/.config/EE_VIDEO_MODE if it's there just remove it.

Also in emulationstation you may have to set a custom resolution and put in: 1280x720p60hz instead of 720p60hz.

Once that is done be sure to restart your device.

Let me know how it goes.

**Comment by Langerz82** [comment] 2022-04-23 04:09
Hey, try this PR and see if it fixes your issue. mount_romfs.sh had a syntax error which may have been breaking the scripts and not allow setres.sh to run properly.

See:
https://github.com/EmuELEC/EmuELEC/pull/904

**Comment by AlienatedDiego** [comment] 2022-04-23 08:56
hi, I did the checks of your first answer with no success. I have no code knowledge, if there is any easy way to get the mount_romfs.sh file I could use it in emuelec/bin to check. thanks for your answers. regards

**Comment by Langerz82** [comment] 2022-04-23 10:41
ok so if your experiencing the issue can someone SSH in and type in the command:
```
emuelec_autostart.sh
```
If no errors are appearing please run the command:
```
bash -x emuelec_autostart.sh
```
And paste all the output in a gist here:
https://gist.github.com/
and provide the link so I can check the debug output? thanks.

**Comment by AlienatedDiego** [comment] 2022-04-23 13:03
EMUELEC:~ # emuelec\_autostart.sh  
rm: can't remove '/storage/.cache/services/bluez.conf': No such file or director                                                                                       y  
find: /media/\*/roms/: No such file or directory  
Using path  
find: /media/\*/roms/: No such file or directory  
find: /media/\*/roms/: No such file or directory  
mv: can't rename '/storage/roms': Device or resource busy  
mount: mounting /dev/mmcblk1p3 on /storage/roms failed: Device or resource busy

**Comment by Langerz82** [comment] 2022-04-23 14:04
ok so it looks like it's not generating any errors.

try going into EmulationStation, setting the resolution to 720p60hz and restarting the device so the bug occurs again.
While it's bugged, SSH in and type the command:
```
setres.sh 720p60hz
```
If the EmulationStation display is still incorrect, try:
```
setres.sh 1280x720p60hz
```
Also use a controller to move with the dpad so EmulationStation tries to refresh. If 1280x720p60hz works for it, we may have to add by default in ES, instead of just 720p60hz.

**Comment by AlienatedDiego** [comment] 2022-04-23 18:47
hey Josh it didn't work.

I think considering that there are more issues besides resolutions for this device and that using the same 4.5 ng image works fine for S905x3 and OdroidN2+ and that an alternative version for Amlogic_old with older kernel is in the kitchen, maybe we should wait until it is ready to try it. Shanti may know the origin of this and other problems.
Thank you for your interest in this matter.

**Comment by Langerz82** [comment] 2022-04-23 20:54
It looks like the ES resolution being picked up is 720p which is correct, however the actual display mode in linux is not changing properly and staying at full HD or more.
Try and run this command and post the output:
```
cat /sys/class/amhdmitx/amhdmitx0/rawedid | /usr/bin/edid-decode | grep -E '^ *VIC' | sed 's/ *VIC  *[0-9]*\://g' | sed 's/^ *//g' | sed 's/ * / /g' | cut -d'.' -f1 | sed 's/i /i/g' | sed 's/ /p/g' | sed -e 's/$/hz/g'
```
The supported resolutions should show up.

**Comment by AlienatedDiego** [comment] 2022-04-23 21:10
1920x1080p50hz  
1920x1080p60hz  
1920x1080p24hz  
1920x1080p25hz  
1920x1080p30hz  
1920x1080i50hz  
1920x1080i60hz  
1280x720p50hz  
1280x720p60hz  
720x576p50hz  
720x576p50hz  
720x480p59hz  
720x480p59hz  
1440x576i50hz  
1440x576i50hz  
1440x480i59hz  
1440x480i59hz  
640x480p59hz

**Comment by Langerz82** [comment] 2022-04-23 21:11
Resolutions look fine, what about this command I posted earlier:
```
bash -x emuelec_autostart.sh
```
Can you run that, it will produce lots of output.

**Comment by AlienatedDiego** [comment] 2022-04-23 21:36
https://pastebin.com/RGkf6fu9

**Comment by Langerz82** [comment] 2022-04-23 21:41
@AlienatedDiego
According to that output you still have 1080p60hz set in your config.
```
++ PAT='^ee_videomode=(.*)'
+++ grep -oE '^ee_videomode=(.*)'
+++ cat /storage/.config/emuelec/configs/emuelec.conf
++ EES=ee_videomode=1080p60hz
++ EES=1080p60hz
++ echo 1080p60hz
+ DEFE=1080p60hz
+ '[' 1080p60hz == Custom ']'
+ setres.sh 1080p60hz
```
Are you sure it was set to 720p and saved in ES?

**Comment by AlienatedDiego** [comment] 2022-04-23 21:42
sorry mi fault...a second

**Comment by AlienatedDiego** [comment] 2022-04-23 21:47
720p https://pastebin.com/Zs7Cm3Ag

**Comment by Langerz82** [comment] 2022-04-23 22:06
@AlienatedDiego 
Hey, and that output was while your were in ES and the display was screwed up right?

**Comment by AlienatedDiego** [comment] 2022-04-23 22:10
I did a new check with setres.sh using a controller to refresh but nothing

![](https://user-images.githubusercontent.com/67949187/164947461-319dc5f4-5d1e-4881-b0c4-97745339f224.PNG)

![](https://user-images.githubusercontent.com/67949187/164947523-452c1a8a-1d2d-4dd3-9f3b-43d816e587d4.jpg)

**Comment by Langerz82** [comment] 2022-04-23 22:12
@AlienatedDiego that is in a game, is EmulationStation the same and corrupt too?

**Comment by AlienatedDiego** [comment] 2022-04-23 22:13
correct.while the problem is displayed on screen and 720p in ES.  
NO.it is the screensaver

**Comment by Langerz82** [comment] 2022-04-23 22:15
On the TV do you have an option were you can see the output resolution on the current HDMI signal? It should be an info button on the TV remote control or something similar.

**Comment by Langerz82** [comment] 2022-04-23 22:21
@AlienatedDiego 
Hey can you also run this following command in SSH:
```
bash -x setres.sh 720p60hz
```
and post output? thanks for your patience.

**Comment by AlienatedDiego** [comment] 2022-04-23 22:22
yes of course, in all cases the TV shows the change of resolution and indeed it shows "720p".

no problem.

**Comment by Langerz82** [comment] 2022-04-23 22:26
Wait so when you press info on the tv remote it says it's displaying in 720p? That's real strange maybe ES is not checking the actual resolution dimensions when starting the screen.

**Comment by Langerz82** [comment] 2022-04-23 22:31
@AlienatedDiego 
hey try this command and see what it does to the output:
```
fbset -fb /dev/fb0 -g 1280 720 1280 720 32
```

**Comment by AlienatedDiego** [comment] 2022-04-23 22:40
mmm does nothing at all.

the tv shows the current resolution and refresh rate of the selected hdmi channel, if i restart emuelec it will show 1080p60hz on the splashscreen (default resolution) when loading the system it changes to the chosen resolution in ES, 720p or whatever. In short, the behavior of the TV is the same in the rest of the devices and versions of emuelec. I don't think this is the case.

please excuse me if I don't explain myself well, I use a translator...

**Comment by AlienatedDiego** [comment] 2022-04-23 22:52
the question is...what do these device(s) differ from the rest. taking into account that all of them are now using the same version 4.5NG and the resolutions work fine in the rest of the devices that I have tried ... I mean that the code is probably fine but these old amlogics work differently than the rest, surely for this reason Shanti is thinking of a specific release for them

**Comment by Langerz82** [comment] 2022-04-23 23:02
I have one idea, not sure if it will work though:
Use SSH, and run the command:
```
nano /emuelec/bin/setres.sh
```
copy and paste this into the file:
https://gist.githubusercontent.com/Langerz82/f9d2b43052b9fe56f287e8cc2c6c645c/raw/79615e4087466d4c6caceffc35bbe6a38866f7ea/setres.sh

save, exit then restart the device.

**Comment by Langerz82** [comment] 2022-04-23 23:15
if it does not work. In that file at the bottom change:
```
[[ "$EE_DEVICE" == "Amlogic-ng" ]] && fbfix
```
to just:
```
fbfix
```
and re-try. I forgot that ng devices suffer from a bug that the buffer is not usually set correctly without that call when SDL is creating it's screen.

**Comment by AlienatedDiego** [comment] 2022-04-23 23:28
ok , the first attempt failed, it took me a while to understand that save(enter) ctrl+x (save)..reboot and it didn't work.  
I can't edit the line from my browser, can you do it for me? Thanks for your patience

**Comment by Langerz82** [comment] 2022-04-23 23:34
run this command:
```
sed -i "s/[[ "$EE_DEVICE" == "Amlogic-ng" ]] && fbfix/fbfix/g" /emuelec/bin/setres.sh
```
will change the line to correct fbfix.

**Comment by AlienatedDiego** [comment] 2022-04-23 23:49
It didn't work. But I can't be 100% sure I did it right. sorry.

![](https://user-images.githubusercontent.com/67949187/164949800-f6129156-627c-4520-9d9e-385c2ef3ad37.PNG)

**Comment by Langerz82** [comment] 2022-04-23 23:53
ah no, try and just run these commands:
```
rm /emuelec/bin/setres.sh
wget https://gist.githubusercontent.com/Langerz82/f9d2b43052b9fe56f287e8cc2c6c645c/raw/4f313c9aab5f461aec2b99069684da113e5fd458/setres.sh /emuelec/bin
chmod +x setres.sh
```
then reboot.

**Comment by AlienatedDiego** [comment] 2022-04-23 23:58
yes...i deleted it because i realized it was wrong.thank you

![](https://user-images.githubusercontent.com/67949187/164949978-8ab28d14-b01b-4331-bfbe-a4202a330be9.PNG)

**Comment by Langerz82** [comment] 2022-04-24 00:00
now reboot did it work?

**Comment by AlienatedDiego** [comment] 2022-04-24 00:05
ok. new attemp

**Comment by AlienatedDiego** [comment] 2022-04-24 00:13
nothing... tell me if you see something wrong, I close ssh before trying

![](https://user-images.githubusercontent.com/67949187/164950298-87720dc0-1064-43cf-9fe0-016dd17356e5.PNG)

**Comment by Langerz82** [comment] 2022-04-24 00:15
run each line separately.

**Comment by AlienatedDiego** [comment] 2022-04-24 00:22
![](https://user-images.githubusercontent.com/67949187/164950474-3665fa37-0858-48a1-9ef5-d69983e8bf9a.PNG)es correcto?

**Comment by Langerz82** [comment] 2022-04-24 00:32
go into the directory with:
```
cd /emuelec/bin
```
then list the files in the directory with
```
ls -la
```
you might have to remove old files with
```
rm setres.sh*
```
then run:
```
wget https://gist.githubusercontent.com/Langerz82/f9d2b43052b9fe56f287e8cc2c6c645c/raw/4f313c9aab5f461aec2b99069684da113e5fd458/setres.sh /emuelec/bin
```
wait till finish, then put:
```
chmod +x /emuelec/bin/setres.sh
```

**Comment by AlienatedDiego** [comment] 2022-04-24 00:38
![](https://user-images.githubusercontent.com/67949187/164950779-40c4f246-cb87-43f2-9959-3e5d1cec3705.PNG)

**Comment by Langerz82** [comment] 2022-04-24 00:45
yep good now reboot

**Comment by AlienatedDiego** [comment] 2022-04-24 00:48
It didn't work but I appreciate all the effort Josh!

**Comment by Langerz82** [comment] 2022-04-24 01:48
@AlienatedDiego I know your probably too tired, but if your still up for it, can you run this command again when you have 720p running?
```
bash -x emuelec_autostart.sh
```
I just want to make sure it's in-fact calling the modified setres.sh you downloaded.

**Comment by AlienatedDiego** [comment] 2022-04-24 02:02
No problem, I'm just sorry I can't be of more help. Thank you for your patience.

https://pastebin.com/VM7awD7Z

**Comment by Langerz82** [comment] 2022-04-24 02:08
I can see that it is, setting 720p mode and fixing the frame buffer with the modified setres.sh. And the resolution is still corrupt in  EmulationStation right? I think shantigilbert may have a better idea of why it still has an error, I'm kinda out of ideas.

```
++ EES=ee_videomode=720p60hz
++ EES=720p60hz
++ echo 720p60hz
+ DEFE=720p60hz
+ '[' 720p60hz == Custom ']'
+ setres.sh 720p60hz
The framebuffer device was opened successfully.
vinfo.yoffset=720
FIX: setting vinfo.yoffset=0.
```

**Comment by AlienatedDiego** [comment] 2022-04-24 02:24
yeah i'm running it now and it's still corrupt, let shanti dig into the problem, maybe he knows where to look. I also take this opportunity to thank you for your contributions with the resolutions and autoconfig of independent systems. really helpful. 

bedtime but available if I can help with anything.

**Comment by Langerz82** [comment] 2022-04-24 02:36
@AlienatedDiego just wondering if you have it set to 720p then you completely shutdown system and pull the plug out. For the first boot does 720p show ok?

**Comment by Langerz82** [comment] 2022-04-24 02:55
I think I have worked it out. mount_romfs restarts the emustation service before setres.sh takes place. so it's trying to run in 720p even though the display is at it's default of 1080p. I have to make some changes and release a PR fix since there are changes to the autostart file.

**Comment by AlienatedDiego** [comment] 2022-04-24 02:59
yes, I have completely turned it off by removing the cable, unfortunately 720p is still broken.

the guy who started the thread must be freaking out

I was remembering a similar issue with broken resolutions 720p and below a long time ago when still on 32bit releases that was discussed on discord, the broken resolution effect was similar, I'll look into it

**Comment by AlienatedDiego** [comment] 2022-04-24 03:00
Oh. Vale.eso tiene sentido

**Comment by Langerz82** [comment] 2022-04-24 03:01
Try this PR and see if it's fixed. You will have to recompile the build.
See:
https://github.com/EmuELEC/EmuELEC/pull/905

**Comment by AlienatedDiego** [comment] 2022-04-24 03:06
Oh ok
that makes sense. Unfortunately I can't do it, as I told you I don't have code knowledge nor do I know how to compile by myself, I only occasionally look for system failures and report them. I'm sorry

quote Shanti to compile a test and I'll try it out asap

**Comment by Langerz82** [comment] 2022-04-24 07:19
Ok so though about this some more, I need someone with the bug to replicate the issue and type a few commands in SSH to see if it fixes it.
So make sure emulationstation you have set the resolution to 720p and that the screen is stuffed as shown like the bug.
Then use a PC to SSH in and do the following commands one at a time:
```
setres.sh 720p60hz
fbfix
systemctl restart emustation
```
And let me know if the screen is still stuffed up.

**Comment by AlienatedDiego** [comment] 2022-04-24 10:30
Same, no change. commands are always entered while the bug is showing (ES 720p60hz)

![](https://user-images.githubusercontent.com/67949187/164972185-5ff7b049-bf83-425e-8a38-290efcda96bd.PNG)

**Comment by Langerz82** [comment] 2022-04-24 12:18
Are you sure EmulationStation is set to 720p60hz? In ssh also do:
```
get_ee_setting ee_videomode
```
720p60hz should return.

**Comment by AlienatedDiego** [comment] 2022-04-24 12:47
yep sure.

EMUELEC:~ # get\_ee\_setting ee\_videomode  
720p60hz

**Comment by Langerz82** [comment] 2022-04-24 13:22
Hey man do you want to Team Viewer so I can try and debug the issue?

**Comment by AlienatedDiego** [comment] 2022-04-24 14:10
no problem, I'll contact you through the forum

**Comment by Langerz82** [comment] 2022-04-24 22:17
I think I've narrowed down the issue to being the call to fbset -fb /dev/fb0 though I don't know how to fix it yet. Even with the fbfix it seems that EmulationStation is not recognising the correct geometry dimensions.

**Comment by Langerz82** [comment] 2022-04-24 23:11
For now if you want to use 720p60hz resolution, unmount the flash directory and add 720p60hz by doing one at a time in SSH:
```
mount -o rw,remount /flash
echo "vout='720p60hz'" >> /flash/config.ini
```
This is a temporary fix until we can find a better solution.

**Comment by AlienatedDiego** [comment] 2022-04-25 08:42
after the checks done (thanks to Langerz) maybe it's not a problem of the code

For my part nothing more, if Shanti manages to compile a test with a different kernel I will try it, hopefully it will fix this and other problems with old Amlogic soc

**Comment by marcus-abreu** [comment] 2022-04-25 17:08
Oh yeah... I really freaked out! I was offline these last few days. I couldn't follow the issue.
You are the best! I'll try the fix later, after work!
Thanks for the effort!

**Comment by Langerz82** [comment] 2022-06-16 09:33
@AlienatedDiego , @marcus-abreu 
Hey do either of you know how to do a PR build, I've changed a few things in resolution switching and I would like to know if this PR fixes your issues with 720p not recognizing.
https://github.com/EmuELEC/EmuELEC/pull/901

**Comment by marcus-abreu** [comment] 2022-06-16 13:54
> @AlienatedDiego , @marcus-abreu Hey do either of you know how to do a PR build, I've changed a few things in resolution switching and I would like to know if this PR fixes your issues with 720p not recognizing. #901

Me neither... sorry!

**Comment by Langerz82** [comment] 2022-09-27 23:35
If anyone who is getting the issue could test with this pull request build I'd be very thankful:
https://github.com/EmuELEC/EmuELEC/pull/1021

**Comment by marcus-abreu** [comment] 2022-12-03 14:44
Hello. I installed the new version 4.6 (clean install) and the error is still there. :-(

**Comment by Langerz82** [comment] 2022-12-03 17:12
did you remove the old setres.sh from /emuelec/bin ?

**Comment by marcus-abreu** [comment] 2022-12-03 18:43
Oh, I see... Thank you anyway!

**Comment by Langerz82** [comment] 2022-12-03 20:03
@marcus-abreu 
Can you try to SSH in and see if the resolution is being accepted in the display mode? SSH in and type:
```
echo 720p60hz > /sys/class/display/mode
```
then check its output:
```
cat /sys/class/display/mode
```
Does it say 720p60hz ? To revert just reboot.

**Comment by marcus-abreu** [comment] 2022-12-04 02:14
@Langerz82, It worked. The resolution changed to 720p instantly.
```console
EMUELEC:~ # echo 720p60hz > /sys/class/display/mode
EMUELEC:~ # cat /sys/class/display/mode
720p60hz
```

**Comment by Langerz82** [comment] 2022-12-04 04:15
@marcus-abreu That is bad as I was hoping it would fail and I could isolate the issue. Ok try this in SSH:
```
bash -x setres.sh 720p60hz
```
It will spit out a heap of data if you could copy/paste the output to gist, I'll see if I can find any issues.
https://gist.github.com/

**Comment by Langerz82** [comment] 2022-12-04 05:17
> @Langerz82, It worked. The resolution changed to 720p instantly.
> 
> ```
> EMUELEC:~ # echo 720p60hz > /sys/class/display/mode
> EMUELEC:~ # cat /sys/class/display/mode
> 720p60hz
> ```

When you say instantly did you mean that EmulationStation appeared fine too? Or did the picture corrupt? Also make sure you move the game controller around so it can do at least one refresh.

**Comment by marcus-abreu** [comment] 2022-12-04 09:00
After running `echo 720p60hz > /sys/class/display/mode`, it changed instantly and fine. Take a look:
![Fine](https://user-images.githubusercontent.com/21199224/205481754-2d768b62-63df-435e-b1c8-c00a44c71f25.jpg)

I also played some SMB3 at 720p:
![So fine](https://user-images.githubusercontent.com/21199224/205481800-31cc9351-4387-423a-8173-67de3e2b8efc.jpg)

After I quit the game, the contents went out of the screen, but with no glitches:
![20221204_052331](https://user-images.githubusercontent.com/21199224/205481839-d7617663-24f7-41f7-ad43-41d88fe4eb44.jpg)

Finally, the `bash -x setres.sh 720p60hz` output:
https://gist.github.com/marcus-abreu/0fd48425f734a6579601835a98ec3c95

Thanks @Langerz82 for the effort!

**Comment by Langerz82** [comment] 2022-12-04 09:52
if you open up and edit the custom_start.sh file in SSH:
```
nano ~/.config/custom_start.sh
```
Find this line and on a line below:
```
# Any commands that you want to run after the frontend has started goes here
```
Add so it looks like this:
```
# Any commands that you want to run after the frontend has started goes here
echo 720p60hz > /sys/class/display/mode
fbfix
```
and if you want to try without the explicit call to 720p and see if the fbfix will fix it just prefix the echo with a hash (disables the line) like so:
```
# Any commands that you want to run after the frontend has started goes here
# echo 720p60hz > /sys/class/display/mode
fbfix
```

**Comment by Langerz82** [comment] 2022-12-04 11:07
I've got a legacy device which I updated and has the same issue so I will try and debug and see what I come up with.

**Comment by marcus-abreu** [comment] 2022-12-04 12:23
@Langerz82, I tried these custom_start changes, but didn't notice any difference.
I'm rooting for you to make it!

**Comment by Langerz82** [comment] 2022-12-05 00:34
Sorry guys I don't think we can fix this. The problem is that for older chips the virtual framebuffer geometry is fixed and locked to 1080p. So when it tries to change the framebuffer to 720p dimensions it changes the physical dimensions but not the virtual dimensions which is causing the screen to corrupt. I even modified fbfix to try and change the virtual size but the kernel doesn't seem to allow the change. I'll fiddle around with it to see if we can still use 720p even though the virtual geometry is different but I'm in doubt there is a fix we can do.

**Comment by shantigilbert** [comment] 2022-12-05 01:04
> Sorry guys I don't think we can fix this. The problem is that for older chips the virtual framebuffer geometry is fixed and locked to 1080p. So when it tries to change the framebuffer to 720p dimensions it changes the physical dimensions but not the virtual dimensions which is causing the screen to corrupt. I even modified fbfix to try and change the virtual size but the kernel doesn't seem to allow the change. I'll fiddle around with it to see if we can still use 720p even though the virtual geometry is different but I'm in doubt there is a fix we can do.

720p can be set at boo on config.ini?

**Comment by Langerz82** [comment] 2022-12-05 01:26
> > Sorry guys I don't think we can fix this. The problem is that for older chips the virtual framebuffer geometry is fixed and locked to 1080p. So when it tries to change the framebuffer to 720p dimensions it changes the physical dimensions but not the virtual dimensions which is causing the screen to corrupt. I even modified fbfix to try and change the virtual size but the kernel doesn't seem to allow the change. I'll fiddle around with it to see if we can still use 720p even though the virtual geometry is different but I'm in doubt there is a fix we can do.
> 
> 720p can be set at boot on config.ini?

@shantigilbert the primary buffer needs to get set and when it tries to set it for 720p it corrupts because the virtual geometry is locked at 1920 3240.

**Comment by shantigilbert** [comment] 2022-12-05 01:35
But the question still remains, does it work if you set it in  boot.ini? Ignoring setres.sh

**Comment by Langerz82** [comment] 2022-12-05 01:54
@shantigilbert 
On vout='720p60hz', with an empty setres.sh file it displays fine but in 4K and the frame buffer is still fixed for 1920x1080.
cat /sys/class/display/mode
2160p60hz
fbset -fb /dev/fb0
mode "1920x1080-0"
	# D: 0.000 MHz, H: 0.000 kHz, V: 0.000 Hz
	geometry 1920 1080 1920 3240 32
	timings 0 0 0 0 0 0 0
	accel false
	rgba 8/16,8/8,8/0,0/24
endmode

**Comment by shantigilbert** [comment] 2022-12-05 01:57
But does it still work? if so, could this not be used as a workaround? maybe detect it in setres.sh and if that is set skip it?

**Comment by Langerz82** [comment] 2022-12-05 02:02
1080p60hz works fine. But I really want a proper fix for 720p60hz and other resolutions suffer the same wrong fixed virtual size. If CoreElec guys dunno either, I might have to make it just use 1080p60hz when EE_DEVICE = Amlogic and anything other than 1080p60hz.

**Comment by shantigilbert** [comment] 2022-12-05 02:04
> If CoreElec guys dunno either,

CoreELEC uses Kodi and that handles the resolution switches, I am sure 720p works fine in CoreELEC so I don't think that is the issue. 

In the meantime a workaround is good enough, don't you think?.

**Comment by Langerz82** [comment] 2022-12-05 02:41
Ok, for now we will force older Amlogic's to run in 1080p60hz. That way a user cant accidentally corrupt the screen by selecting another resolution, unless we find a proper solution.
See:
https://github.com/EmuELEC/EmuELEC/pull/1071

**Comment by marcus-abreu** [comment] 2022-12-07 23:03
I don't know Emuelec's architecture, but it is possible to deduce some questions. I left the default resolution in Emuelec's video mode and set 720p60Hz in NES emulator's native video. Thus, Emulationstation was fine, but within Retroarch there was the glitch. Could it be that the problem is in a layer below, common to the 2 systems? Maybe in the OS driver? Sorry for the amateur comment.

**Comment by marcus-abreu** [comment] 2022-12-09 13:25
> CoreELEC uses Kodi and that handles the resolution switches, I am sure 720p works fine in CoreELEC so I don't think that is the issue.

Yeap. Just installed the last CoreELEC version and the resolution switches works fine.

**Comment by Langerz82** [comment] 2022-12-10 12:19
I installed CoreElec v20 to test as well. 720p is actually simulated, The bug occurs in it as well and the virtual buffer is fixed and set too:
```
mode "1280x720-0"
	# D: 0.000 MHz, H: 0.000 kHz, V: 0.000 Hz
	geometry 1280 720 1920 3240 32
	timings 0 0 0 0 0 0 0
	accel false
	rgba 8/16,8/8,8/0,0/24
endmode
```
If fiddled with the settings to try and get it to change without corrupting like in CoreELEC. No luck so far.

**Comment by Langerz82** [comment] 2022-12-10 23:13
This PR emulates 720p however there are issues:
https://github.com/EmuELEC/EmuELEC/pull/1071#issuecomment-1345405363

**Comment by Langerz82** [comment] 2022-12-20 10:20
Bad News:
This issue cant be fixed. If you need an image that supports 720p60hz or below you will have to use EmuELEC 4.3.

ref:
https://discourse.coreelec.org/t/coreelec-20-framebuffer-errors-for-amlogic-s905w-and-below/19859/6

**Comment by Langerz82** [comment] 2023-04-11 22:10
Think I have a really good idea. This is not a full fix but a workaround so you can update to the latest Emuelec and display different resolutions. Internally it will still run 1920x1080 for the buffer, but the output will actually be whatever resolution you set it too at.

This is experimental and will need testing. PR in a bit.

**Comment by Langerz82** [comment] 2023-04-12 11:59
Here is a test release which should theoretically allow you to change resolutions and still be able to use 4.6. You can get the build release here:
https://github.com/Langerz82/EmuELEC/releases/tag/v4.6.amlogic

**Comment by Langerz82** [comment] 2023-04-21 23:32
I stumbled upon a solution looking through the older distro's. It has a limitation it cant run 4K mode but you wouldnt want to anyway as the device would be slowwwww.

see:
https://github.com/EmuELEC/EmuELEC/pull/1171

**Comment by Langerz82** [comment] 2023-05-02 01:37
resolved in latest version.

**Closed by Langerz82** 2023-05-02 01:37 UTC
