### ISSUE TITLE
Emuelec stopped working - X96 Max+ @2G/16G

### ISSUE THREAD

**Issue by CharlieSalinas** [EmuELEC/EmuELEC#471] opened 2021-02-16 06:27 UTC
I am sharing my problem since it might help people with same problem or similar journey with same tvbox model.

TRICKY INSTALL
I finally got working Emuelec with all the possible emulators (but not SNES/Dreamcast, was still resolving this). 
I used the latest ng version and got some difficult time trying to run the initial boot since the toothpick was not rooting to Emuelec. TV Box was going to its original software or freezing at splash screen logo. I thought that I could have the wrong file since I read that sometimes they change the chips on cheap tv boxes, so I confirm my chipset and ram with the process described at Wiki. Once I knew I did had the right file, I assumed that the resetting wasn't going thru. 

RESET PROCESS
I downloaded an app thru device Play Store "Librelec" and finally got the Emuelec Installation Screen.

CONFIGURING EMUELEC
Uploading roms was easy peacey, running them was complicated since some of them need emulators.
Again, I just follow the Wiki and install all the bios on its right path (most of them are very easy to find by Google search).
Romscrapped my roms and got all the artwork/videos/reviews out of them.
Installed the netflix look alike theme. Even tested most of the emulators and found issues just at dreamcast and snes.

------------------------------------------
THE PROBLEM
TV BOX CRASHED?
While testing my sweet installation, I notice that my hotkey stopped working and couldnt get out of games and had to reset by powering off tvbox. This happened while testing PS1 roms for the first time, they run but couldnt get outside of it. First reboot got stuck at tvbox splashscreen, it didnt load up Emuelec at all. So I powercycled and got Emuelec running again. I continue testing PS1 games and all of the sudden I couldnt move anything at all  anymore. Tried to power cicled cant get passed the Emuelec splash screen or tvbox logo.

I open up SD card and there where 2 new empty folders named "LOST.DIR" (empty folder)  and "ANDROID" folder with a "data" folder, with 3 emty folders "com.abupdate.fota_demo_iot" "com.google.android.gms", and another file named ".nomedia" that looked empty by its weight. I deleted them. Try boot, no succes. 

I noticed that roms/bios configured where not at sd card, so I format it and mount again the image. Try boot, no success.
And here I am now, not able to get the installation running again.
I did notice during the installation of roms that I reached the limit space of the device I was transferring my roms to tvbox. And after that I continue downloading romscrapes. 

I am trying to reinstall with no success.
I tried accessing the tvbox with its IP like I did with Emuelec, but it doesnt allow me to do so. So I cant check any file inside or the roms folder.

Any suggestions?
I appreciate very much the Emuelec team and Shantigilbert for their work.
--------
continue troubleshoot
SD card got corrupted
Formatted and mounted image again. try boot. no success.
Went to sd card on windows, and while trying to fix by "Right click > properties > tools > check disk". I did noticed that my sd card  total volume was 2GB instead of 32GB.
Tried chkdsk thru command prompt and got messaged "sd card file system is raw".
followed this instrutions at command prompt (CMD):
https://www.diskpart.com/diskpart/the-type-of-the-file-system-is-raw-sd-card-3889.html

This format recovered to full partition of 32GB.
I re-mount the ng emuelec image, and try to run Emuelec, but is not booting again, I am guessing my installation files at tvbox got corrupted.

I will reset tv box to factory settings and will try to run installation from zero again. To see if a brand new install will make it run Emuelec again.

**Comment by shantigilbert** [comment] 2021-02-17 20:08
These particular device (x96) which in turn is a LOT of different devices with many different components seem to have a lot of issues that I never faced anywhere else nor do I know how to solve, please look around the issues opened here by other users. 

These are my recommendations: 

- Try another flashing software (etcher, win32diskimager, etc)
- Try another SD or SD card reader
- Use a USB pen drive (just for testing as these tend to be very slow)

if none of that works, then I am sorry I have no idea. 

I will close this and mark it as duplicate of #439 but you can look around as well for other issues regarding this hideous box.

**Closed by shantigilbert** 2021-02-17 20:08 UTC
