### ISSUE TITLE
Time synchronized error

### ISSUE THREAD

**Issue by stats121** [EmuELEC/EmuELEC#364] opened 2020-12-07 22:23 UTC
**Describe the bug**
Time synchronized error appears frequently between load screens in Odroid Go Advance on v3.9

**To Reproduce**
Happens at start-up or when loading an Emulator

**Expected behavior**
No failure

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/50186176/101412633-d73c2080-38da-11eb-840c-7e7153650cbd.jpg)

**EmuELEC version:**
v3.9

**Comment by shantigilbert** [comment] 2020-12-07 22:55
That is really not a bug, Timesync needs internet to work correctly , it is annoying tho, and I will try to find another way to do it, but for the time being, there is nothing to fix.

**Comment by hardknoxni69a** [comment] 2021-01-24 19:43
how is this not considered high priority when it effectively freezes our system forcing a hard reboot on our SD card? I may be missing something but how am I supposed to restart when this kills the system?

**Comment by shantigilbert** [comment] 2021-01-24 19:49
@hardknoxni69a whatever it is that is causing your freezes is not related to this, just because you see it on screen it does not mean it's the issue

**Comment by hardknoxni69a** [comment] 2021-01-25 00:06
It is a fresh flash so not sure what would be causing the issue. But ya the only thing I see on screen is the timer error. How do I fix the time

**Comment by shantigilbert** [comment] 2021-02-14 01:32
Fixed in v4.0

**Closed by shantigilbert** 2021-02-14 01:32 UTC
Labels: Low Priority
