### ISSUE TITLE
Make:host build error

### ISSUE THREAD

**Issue by pjessop** [EmuELEC/EmuELEC#746] opened 2021-10-21 09:36 UTC
Hi, I'm excited by this project and keen to potentially contribute, but trying to build from source, I'm getting a make:host error very early on:

```
mv -f .deps/remake.Tpo .deps/remake.Po
mv -f .deps/variable.Tpo .deps/variable.Po
mv -f .deps/read.Tpo .deps/read.Po
/usr/bin/gcc  -march=native -O2 -Wall -pipe -I/home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/toolchain/include -Wno-format-security -Wl,--export-dynamic -Wl,-rpath,/home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/toolchain/lib -L/home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/toolchain/lib -o make ar.o arscan.o commands.o default.o dir.o expand.o file.o function.o getopt.o getopt1.o guile.o implicit.o job.o load.o loadapi.o main.o misc.o posixos.o output.o read.o remake.o rule.o signame.o strcache.o variable.o version.o vpath.o hash.o remote-stub.o glob/libglob.a   
/usr/bin/ld: glob/libglob.a(glob.o): in function `glob_in_dir':
glob.c:(.text+0x82d): undefined reference to `__stat'
/usr/bin/ld: glob/libglob.a(glob.o): in function `glob':
glob.c:(.text+0xd98): undefined reference to `__stat'
/usr/bin/ld: glob.c:(.text+0x15b7): undefined reference to `__stat'
/usr/bin/ld: glob.c:(.text+0x190e): undefined reference to `__stat'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:656: make] Error 1
make[3]: Leaving directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/make-4.2.1/.x86_64-linux-gnu'
make[2]: *** [Makefile:798: all-recursive] Error 1
make[2]: Leaving directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/make-4.2.1/.x86_64-linux-gnu'
make[1]: *** [Makefile:534: all] Error 2
make[1]: Leaving directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/make-4.2.1/.x86_64-linux-gnu'
**FAILURE: scripts/build make:host has failed!
[002/483] [FAIL] build   make:host**

The following logs for this failure are available:
  stdout: /home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/.threads/logs/2/stdout
  stderr: /home/paul/EmuELEC/build.EmuELEC-Amlogic.aarch64-4.3/.threads/logs/2/stderr

parallel: This job failed:
package_worker 2 2 483 'build make:host'
Parallel build failure - see log for details. Time of failure: Wed Oct 20 23:53:43 BST 2021
make: *** [Makefile:12: image] Error 1
```

I folowed steps exactly and installed the dependencies as stated by Shanti + upgraded and updated Ubuntu. I'm using Linux on a 128gb HD, 8mb RAM, free HD around 100gb. I presume these specs are more than enough.

I followed the build prerequisites and executed..

$ git clone https://github.com/shantigilbert/EmuELEC.git
$ cd EmuELEC
$ git checkout master
$ PROJECT=Amlogic ARCH=aarch64 DISTRO=EmuELEC make image

Any advice to get me past package 2 :-) would be really appreciated.

Many Thanks

**Comment by miwasp** [comment] 2021-10-21 09:52
Is this on Ubuntu 21.04?
There was someone on discord with the same error. The solution was to build with 18.04 or 20.04.

**Comment by shantigilbert** [comment] 2021-10-21 18:14
> I'll hopefully wait for a fix on the current Ubuntu to try out this project. I've got too much running on this version & would need to VM my Windows PC which is a hassle and VM has all kinds of it's own issues such as memory allocation and ram issues for building projects from source.

If you know your way around compiling, maybe you could update the packages that are erroring out with newer versions in this case `make` which is compiled with this package.mk https://github.com/EmuELEC/EmuELEC/blob/dev/packages/devel/make/package.mk and try again, but I suspect this will not be the only issue you face.

A lot of the packages included are older than what is currently available (e.g GCC is 8.3) I assume Ubuntu 21 has moved to newer versions thus making it fail on compiling.

**Comment by pjessop** [comment] 2021-10-21 21:03
> > I'll hopefully wait for a fix on the current Ubuntu to try out this project. I've got too much running on this version & would need to VM my Windows PC which is a hassle and VM has all kinds of it's own issues such as memory allocation and ram issues for building projects from source.
> 
> If you know your way around compiling, maybe you could update the packages that are erroring out with newer versions in this case `make` which is compiled with this package.mk https://github.com/EmuELEC/EmuELEC/blob/dev/packages/devel/make/package.mk and try again, but I suspect this will not be the only issue you face.
> 
> A lot of the packages included are older than what is currently available (e.g GCC is 8.3) I assume Ubuntu 21 has moved to newer versions thus making it fail on compiling.

Sure, I'll have a go!!

**Comment by miwasp** [comment] 2021-10-30 15:52
I get the same error if i try to compile with the new build system.
I'm using Ubuntu 20.04 with latest patches. I'm trying this on the same system which compiles successful with the 'old' build system.
@shantigilbert If it's working for you, can you please give us a list of installed packages according to readline, ncurses and tinfo on your system? Maybe its really just a missing package.

**Comment by shantigilbert** [comment] 2021-10-30 17:45
> 
> 
> I get the same error if i try to compile with the new build system. I'm using Ubuntu 20.04 with latest patches. I'm trying this on the same system which compiles successful with the 'old' build system. @shantigilbert If it's working for you, can you please give us a list of installed packages according to readline, ncurses and tinfo on your system? Maybe its really just a missing package.

I do not use Ubutu 20+ I use Ubuntu 18 and it compiles fine. I would need to set up another computer with 20+ so I can properly test.

but on 18.04

```
dpkg -l '*ncurses*' | grep '^ii'
ii  libncurses5:amd64     6.1-1ubuntu1.18.04 amd64        shared libraries for terminal handling
ii  libncurses5-dev:amd64 6.1-1ubuntu1.18.04 amd64        developer's libraries for ncurses
ii  libncursesw5:amd64    6.1-1ubuntu1.18.04 amd64        shared libraries for terminal handling (wide character support)
ii  ncurses-base          6.1-1ubuntu1.18.04 all          basic terminal type definitions
ii  ncurses-bin           6.1-1ubuntu1.18.04 amd64        terminal-related programs and man pages
```

```
dpkg -l '*tinfo*' | grep '^ii'
ii  libtinfo-dev:amd64 6.1-1ubuntu1.18.04 amd64        developer's library for the low-level terminfo library
ii  libtinfo5:amd64    6.1-1ubuntu1.18.04 amd64        shared low-level terminfo library for terminal handling
```

```
dpkg -l '*readline*' | grep '^ii'
ii  libreadline7:amd64         7.0-3        amd64        GNU readline and history libraries, run-time libraries
ii  readline-common            7.0-3        all          GNU readline and history libraries, common files
```

**Comment by miwasp** [comment] 2021-10-30 22:53
On 20.04 it is the same except for newer versions.

```
dpkg -l '*ncurses*' | grep '^ii'
ii  libncurses-dev:amd64 6.2-0ubuntu2 amd64        developer's libraries for ncurses
ii  libncurses6:amd64    6.2-0ubuntu2 amd64        shared libraries for terminal handling
ii  libncursesw6:amd64   6.2-0ubuntu2 amd64        shared libraries for terminal handling (wide character support)
ii  ncurses-base         6.2-0ubuntu2 all          basic terminal type definitions
ii  ncurses-bin          6.2-0ubuntu2 amd64        terminal-related programs and man pages
```
```
dpkg -l '*tinfo*' | grep '^ii'
ii  libtinfo-dev:amd64 6.2-0ubuntu2 amd64        transitional package for libncurses-dev
ii  libtinfo6:amd64    6.2-0ubuntu2 amd64        shared low-level terminfo library for terminal handling
```
```
dpkg -l '*readline*' | grep '^ii'
ii  libreadline8:amd64         8.0-4        amd64        GNU readline and history libraries, run-time libraries
ii  readline-common            8.0-4        all          GNU readline and history libraries, common files
```

This is what i found out so far:
libncurses was split into libncurses and libtinfo anytime in the past. Programs that used to compile with only "-lncurses" had to use "-lncurses -ltinfo" until then. If i add libtinfo.so in the file link.txt somewhere in the build-tree, ecwolf compiles fine. To avoid further problems, most Linux systems (including Ubuntu) replace the shared lib "libncurses.so" with a file with the content:
`INPUT(libncurses.so.6 -ltinfo)`

This instructs a program that uses libncurses to automatically link against libtinfo also. I think this is done in 18.04 the same way.

Now to the actual problem: If the error was raised based on the ncurses package on the HOST, then it would also be raised with the "old" build system in my case (both environments run on the same machine with the same packages).
So i think its not the packages on the HOST but the packages in the toolchain. In fact there are changes in the ncurses package between old and new build system (e.g. there were no shared libs generated in the "old" system).  This would explain why it works with the "old" build system but not with the new one on MY system.

What i don't get is why it is running in your environment?

**Comment by shantigilbert** [comment] 2021-10-30 23:26
>  In fact there are changes in the ncurses package between old and new build system (e.g. there were no shared libs generated in the "old" system).

Maybe revert the ncurses package and try again? or update ecwolf to the newest git? 

> What i don't get is why it is running in your environment? 

I am 100% sure is host related somehow, but I do not know exactly, since if it was NOT and it was toolchain related then it would not work for anyone.

**Comment by shantigilbert** [comment] 2021-10-30 23:27
I will try to setup a Ubuntu 21 machine tomorrow, compilation will be slow, but I can properly test and see if I can come up with a solution

**Comment by shantigilbert** [comment] 2021-10-30 23:32
Also, can someone try to put this on ecwolf package

`PKG_DEPENDS_HOST="toolchain:host SDL2_mixer:host SDL2_net:host"`

**Comment by miwasp** [comment] 2021-10-31 00:03
> Also, can someone try to put this on ecwolf package
> 
> `PKG_DEPENDS_HOST="toolchain:host SDL2_mixer:host SDL2_net:host"`

Same error.

**Comment by shantigilbert** [comment] 2021-10-31 05:50
I just build EmuELEC on a clean install of Ubuntu 21 (normal installation) and ecwolf compiled fine, so there is something else that is conflicting between your computer and the build system, question is, what?. But another thing you guys can try is removing the `ecwolf:host` dep, I think its not even needed. 

In the end the only reason we needed the `ecwolf:host` is for 2 binaries, but those are already compiled with `ecwolf:target`
https://github.com/EmuELEC/EmuELEC/blob/EE_CE_20/packages/sx05re/emulators/ecwolf/package.mk#L34
https://github.com/EmuELEC/EmuELEC/blob/EE_CE_20/packages/sx05re/emulators/ecwolf/package.mk#L37 

So maybe try removing the `ecwolf:host` from the ecwolf package.mk I am going to do this test as well, but the computer I set up for this test is very slow, so doing a clean build takes a few more hours than usual.

**Comment by miwasp** [comment] 2021-10-31 10:11
> I just build EmuELEC on a clean install of Ubuntu 21 (normal installation) and ecwolf compiled fine,

"normal" means with GUI?
My installation is WSL2 with a fresh Ubuntu 20.04 server (without GUI). Maybe ncurses is not used in an environment with GUI?
> 
> So maybe try removing the `ecwolf:host` from the ecwolf package.mk.

Doesn't work. ecwolf:host is needed to create the file "ImportExecutables.cmake" which is then used by ecwolf:target.

@pjessop Can you please describe your system? Physical or virtual? WSL? Server or with GUI?

**Comment by pjessop** [comment] 2021-10-31 22:52
@miwasp I'm running a GUI latest version Ubuntu 21 on a physical 1gb HD (not partitioned, not WSL, not VM).

As for packages, I can run an '--installed' command and list the full set in a post, but I guess that's a bit overkill and probably not that useful? It'll be huge too.

The related packages to this conversation installed on my system are:

libncurses-dev/impish,now 6.2+20201114-2build1 amd64 [installed,automatic]
libncurses5-dev/impish,now 6.2+20201114-2build1 amd64 [installed]
libncurses5/impish,now 6.2+20201114-2build1 i386 [installed]
libncurses6/impish,now 6.2+20201114-2build1 amd64 [installed]
libncursesw6/impish,now 6.2+20201114-2build1 amd64 [installed,automatic]
libndp0/impish,now 1.8-0ubuntu2 amd64 [installed,automatic]
.
.
ncurses-base/impish,impish,now 6.2+20201114-2build1 all [installed]
ncurses-bin/impish,now 6.2+20201114-2build1 amd64 [installed]

**Comment by shantigilbert** [comment] 2021-11-01 03:15
> @miwasp I'm running a GUI latest version Ubuntu 21 as the only OS on a physical 1gb HD (not partitioned, not WSL, not VM, not used as a server).
> 
> As for packages, I can run an '--installed' command and list the full set in a post, but I guess that's a bit overkill and probably not that useful? It'll be huge too.
> 
> The related packages to this conversation installed on my system are:
> 
> libncurses-dev/impish,now 6.2+20201114-2build1 amd64 [installed,automatic] libncurses5-dev/impish,now 6.2+20201114-2build1 amd64 [installed] libncurses5/impish,now 6.2+20201114-2build1 i386 [installed] libncurses6/impish,now 6.2+20201114-2build1 amd64 [installed] libncursesw6/impish,now 6.2+20201114-2build1 amd64 [installed,automatic] libndp0/impish,now 1.8-0ubuntu2 amd64 [installed,automatic] . . ncurses-base/impish,impish,now 6.2+20201114-2build1 all [installed] ncurses-bin/impish,now 6.2+20201114-2build1 amd64 [installed]
> 
> Othr things I've tried:
> 
>     * Installing libncurses from source (latest v6) = installed fine but still same compile issue.
> 
>     * uninstalling libncurses6 and installing libncurses5 instead = all fine but same compile issue
> 
> 
> Let me know if there's anything you'd like me to try..

was it a clean install? or an upgrade? just trying to figure out all the options, since I just tested a clean install of Ubuntu 21 and it works fine :/ (at least ecwolf compiled, I did not finish the compilation of the imge because I was running it on an old laptop)

**Comment by miwasp** [comment] 2021-11-01 16:16
And now it gets even more strange.
I grabbed an old notebook and made a fresh "normal install" of Ubuntu 21.10 Desktop on it.
- configured wifi connection
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc
- git clone https://github.com/EmuELEC/EmuELEC
- cd EmuELEC
- git checkout EE_CE_20
- PROJECT=Amlogic-ce DEVICE=Amlogic-ng ARCH-aarch64 DISTRO=EmuELEC make image

ecwolf:host failed.

**Comment by shantigilbert** [comment] 2021-11-01 16:19
> 
> 
>     * sudo apt install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc

I only used `sudo apt install gcc make git` so maybe it is something on one of those packages?

**Comment by miwasp** [comment] 2021-11-01 18:10
I deinstalled all those packages and started again:
- sudo apt remove gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc
- sudo apt-get autoremove
- sudo apt install gcc make git
- rm -rf EmuELEC/

and started again with "git clone...".
This time libsdl12-compat:host failed, After installing libsdl2-dev with all its dependencies it continued until ecwolf:host, which failed again.

**Comment by shantigilbert** [comment] 2021-11-01 19:07
@miwasp @pjessop I can 100% confirm one of those packages is the culprit.

Here is my test scenario:

* Clean install Ubuntu 21
* `sudo apt install gcc make git`
* git clone and `make image` follow instructions to install missing deps

`ecwolf:host` compiles fine no issues

Now as soon as I do 
```
sudo apt install gcc make git unzip wget xz-utils libsdl2-dev libsdl2-mixer-dev libfreeimage-dev libfreetype6-dev libcurl4-openssl-dev rapidjson-dev libasound2-dev libgl1-mesa-dev build-essential libboost-all-dev cmake fonts-droid-fallback libvlc-dev libvlccore-dev vlc-bin texinfo premake4 golang libssl-dev curl patchelf xmlstarlet default-jre xsltproc
```
And do 
```
./scripts/clean ecwolf 
make image
```
Now the same error you guys are getting is now present and `ecwolf:host` fails. 

uninstalling the packages makes no difference, I guess a purge of those packages might bee needed, but I think it is overkill, we need to find the specific package that is causing this error

**Comment by miwasp** [comment] 2021-11-01 19:20
I just reinstalled my system and only installed gcc, make and git. Its currently compiling.
If it compiles ecwolf:host this time, i will install the other packages one at a time with "clean ecwolf" and "make image".
If i know what package it is, i will let you know.

**Comment by shantigilbert** [comment] 2021-11-01 19:21
Found the culprit at least on my system

try this:

```
sudo apt purge libsdl2-mixer-dev
```

**Comment by shantigilbert** [comment] 2021-11-01 22:57
Just pushed a fix for ecwolf: https://github.com/EmuELEC/EmuELEC/commit/f72c922fc965ffebf0b62dc819cc2a5d93655781

**Comment by pjessop** [comment] 2021-11-02 11:00
> Just pushed a fix for ecwolf: [f72c922](https://github.com/EmuELEC/EmuELEC/commit/f72c922fc965ffebf0b62dc819cc2a5d93655781)

This seems to have worked :-)

I've just past this package on the build and into the 90s.

**Comment by shantigilbert** [comment] 2021-11-02 19:53
> > Just pushed a fix for ecwolf: [f72c922](https://github.com/EmuELEC/EmuELEC/commit/f72c922fc965ffebf0b62dc819cc2a5d93655781)
> 
> This seems to have worked :-)
> 
> I've just past ecwolf on the build and into the 90s.

@miwasp discovered another error that was just fixed, so pull the latest changes :)

**Comment by pjessop** [comment] 2021-11-02 20:30
> > > Just pushed a fix for ecwolf: [f72c922](https://github.com/EmuELEC/EmuELEC/commit/f72c922fc965ffebf0b62dc819cc2a5d93655781)
> > 
> > 
> > This seems to have worked :-)
> > I've just past ecwolf on the build and into the 90s.
> 
> @miwasp discovered another error that was just fixed, so pull the latest changes :)

Many thanks. Just pulling latest version.

It powered through to 277 this time and failed on qt-everywhere:target. Hopefully that's the error @miwasp reported.

**Comment by pjessop** [comment] 2021-11-02 22:12
> > > > Just pushed a fix for ecwolf: [f72c922](https://github.com/EmuELEC/EmuELEC/commit/f72c922fc965ffebf0b62dc819cc2a5d93655781)
> > > 
> > > 
> > > This seems to have worked :-)
> > > I've just past ecwolf on the build and into the 90s.
> > 
> > 
> > @miwasp discovered another error that was just fixed, so pull the latest changes :)
> 
> Many thanks. Just pulling latest version.
> 
> It powered through to 277 this time and failed on qt-everywhere:target. Hopefully that's the error @miwasp reported.

ahh, i've regressed back to 152 on this build. Seems to be: /usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0)

relevant section of log..

SHIPPED scripts/dtc/dtc-parser.tab.h
  SHIPPED scripts/dtc/dtc-parser.tab.c
  HOSTCC  scripts/dtc/dtc-lexer.lex.o
  HOSTCC  scripts/dtc/dtc-parser.tab.o
  HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [scripts/Makefile.host:110: scripts/dtc/dtc] Error 1
make[2]: *** [scripts/Makefile.build:648: scripts/dtc] Error 2
make[1]: *** [Makefile:564: scripts] Error 2
make[1]: Leaving directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/linux-786bc061aa7ee8378d15d38dd51dbdd6e2308dc1'
FAILURE: scripts/build linux:target during make_target (package.mk)
*********** FAILED COMMAND ***********
kernel_make modules
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install linux:target has failed!

The following log for this failure is available:
  /home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/.threads/logs/151.log

>>> linux:target seq 151 >>>
[152/524] [FAIL] install linux:target

The following log for this failure is available:
  /home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/.threads/logs/151.log

**Comment by shantigilbert** [comment] 2021-11-03 00:02
@pjessop I was pretty sure I fixed the dtc issue... but maybe I am wrong as I cannot see the commit.

Anyways, the fix is this patch: https://github.com/Tomoms/android_kernel_oppo_msm8974/commit/11647f99b4de6bc460e106e876f72fc7af3e54a6.patch place it in the `patches` folder with the `dtc` package

**Comment by shantigilbert** [comment] 2021-11-03 01:55
I just pushed a fix for qt-everywhere I am not sure why dtc is failing for you, it worked fine for me on Ubuntu 21, but the patch I posted above should do the trick either way.

**Comment by pjessop** [comment] 2021-11-03 19:32
> I just pushed a fix for qt-everywhere I am not sure why dtc is failing for you, it worked fine for me on Ubuntu 21, but the patch I posted above should do the trick either way.

have put patch in /dtc/patches, but now get this error:

[066/525] [DONE] build   pcre:host
<<< dtc:host seq 64 <<<
CLEAN      dtc
    *      Removing /home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/dtc-1.6.0 ...
UNPACK      dtc
    APPLY PATCH (common)      packages/tools/dtc/patches/11647f99b4de6bc460e106e876f72fc7af3e54a6.patch
can't find file to patch at input line 49
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 11647f99b4de6bc460e106e876f72fc7af3e54a6 Mon Sep 17 00:00:00 2001
|From: Dirk Mueller <dmueller@suse.com>
|Date: Tue, 14 Jan 2020 18:53:41 +0100
|Subject: [PATCH] scripts/dtc: Remove redundant YYLOC global declaration
|
|commit e33a814e772cdc36436c8c188d8c42d019fda639 upstream.
|
|gcc 10 will default to -fno-common, which causes this error at link
|time:
|
|  (.text+0x0): multiple definition of `yylloc'; dtc-lexer.lex.o (symbol from plugin):(.text+0x0): first defined here
|
|This is because both dtc-lexer as well as dtc-parser define the same
|global symbol yyloc. Before with -fcommon those were merged into one
|defintion. The proper solution would be to to mark this as "extern",
|however that leads to:
|
|  dtc-lexer.l:26:16: error: redundant redeclaration of 'yylloc' [-Werror=redundant-decls]
|   26 | extern YYLTYPE yylloc;
|      |                ^~~~~~
|In file included from dtc-lexer.l:24:
|dtc-parser.tab.h:127:16: note: previous declaration of 'yylloc' was here
|  127 | extern YYLTYPE yylloc;
|      |                ^~~~~~
|cc1: all warnings being treated as errors
|
|which means the declaration is completely redundant and can just be
|dropped.
|
|Signed-off-by: Dirk Mueller <dmueller@suse.com>
|Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
|[robh: cherry-pick from upstream]
|Cc: stable@vger.kernel.org
|Signed-off-by: Rob Herring <robh@kernel.org>
|[nc: Also apply to dtc-lexer.lex.c_shipped due to a lack of
|     e039139be8c2, where dtc-lexer.l started being used]
|Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>
|Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
|Change-Id: I7f299451e99aab09375883546e47505ec0937c26
|---
| scripts/dtc/dtc-lexer.l             | 1 -
| scripts/dtc/dtc-lexer.lex.c_shipped | 1 -
| 2 files changed, 2 deletions(-)
|
|diff --git a/scripts/dtc/dtc-lexer.l b/scripts/dtc/dtc-lexer.l
|index c600603044f..cf7707be43a 100644
|--- a/scripts/dtc/dtc-lexer.l
|+++ b/scripts/dtc/dtc-lexer.l
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 61
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/scripts/dtc/dtc-lexer.lex.c_shipped b/scripts/dtc/dtc-lexer.lex.c_shipped
|index 2c862bc86ad..e3663ce1af5 100644
|--- a/scripts/dtc/dtc-lexer.lex.c_shipped
|+++ b/scripts/dtc/dtc-lexer.lex.c_shipped
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
*********** FAILED COMMAND ***********
patch -d "${PKG_BUILD}" -p1 < ${i} 1>&${VERBOSE_OUT}
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/build dtc:host has failed!

The following log for this failure is available:
  /home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/.threads/logs/64.log

>>> dtc:host seq 64 >>>
[067/525] [FAIL] build   dtc:host

**Comment by shantigilbert** [comment] 2021-11-03 20:08
Yeah that dtc patch is not for that package, I think its somewhere else, but I am using Ubuntu 21 and I cannot reproduce it, so not sure where it should go. I lefy my laptop compiling overnight and it finished correctly (with some minor changes unrelated to your errors) 

So I am a bit lost

**Comment by pjessop** [comment] 2021-11-03 22:40
very strange!! I deleted 'EmuELEC' and re-cloned from your github and ran 'make image' again and got same error but on package 156, instead of erroring out at 152:

`[152/525] [DONE] install corefonts:target
<<< expat:target seq 160 <<<
INSTALL      expat (target)
>>> expat:target seq 160 >>>
[153/525] [DONE] install expat:target
<<< libmnl:target seq 161 <<<
INSTALL      libmnl (target)
>>> libmnl:target seq 161 >>>
[154/525] [DONE] install libmnl:target
<<< libnftnl:target seq 162 <<<
INSTALL      libnftnl (target)
>>> libnftnl:target seq 162 >>>
[155/525] [DONE] install libnftnl:target
<<< linux:target seq 132 <<<
BUILD      linux (target)
    TOOLCHAIN      make (auto-detect)
Cloning into 'exfat-linux'...
Switched to a new branch 'old'
Branch 'old' set up to track remote branch 'old' from 'origin'.
make[1]: Entering directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/linux-786bc061aa7ee8378d15d38dd51dbdd6e2308dc1'
scripts/kconfig/conf  --oldconfig Kconfig
#
# configuration written to .config
#
make[1]: Leaving directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/linux-786bc061aa7ee8378d15d38dd51dbdd6e2308dc1'
make[1]: Entering directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/linux-786bc061aa7ee8378d15d38dd51dbdd6e2308dc1'
scripts/kconfig/conf  --silentoldconfig Kconfig
  CHK     include/config/kernel.release
  CHK     include/config/kernel.release_full
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  HOSTLD  scripts/dtc/dtc
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make[3]: *** [scripts/Makefile.host:110: scripts/dtc/dtc] Error 1
make[2]: *** [scripts/Makefile.build:648: scripts/dtc] Error 2
make[1]: *** [Makefile:564: scripts] Error 2
make[1]: *** Waiting for unfinished jobs....
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
make[1]: Leaving directory '/home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/build/linux-786bc061aa7ee8378d15d38dd51dbdd6e2308dc1'
FAILURE: scripts/build linux:target during make_target (package.mk)
*********** FAILED COMMAND ***********
kernel_make modules
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install linux:target has failed!

The following log for this failure is available:
  /home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/.threads/logs/132.log

>>> linux:target seq 132 >>>
[156/525] [FAIL] install linux:target
`

**Comment by shantigilbert** [comment] 2021-11-03 23:15
So I see the same error for yylloc
```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here
``` 

So I assume that patch I showed you should go into the `linux` package the one in `projects/amlogic-ce/packages/linux` (or on `projects/amlogic-ce/devices/amlogic-ng/patches/linux`, but I am snot sure why do you even need it as I am on Ubuntu 21 and I do not need it

**Comment by pjessop** [comment] 2021-11-04 18:52
That patch worked great in `/projects/amlogic-ce/packages/linux` but like you say, odd that I even needed it.

I'm now almost at the finish line but seems an SSL cert has run out and effected the pull from package 476 (eduke), log below.

Anyway around this?? Seems the 3rd party site is unaccessible.

I really hope I can get past this probable final hurdle.

I've run 'make image' quite a few times to see if the connection resolves but alas, always failing on 476 now.

```
[475/525] [DONE] install soniccd:target
<<< eduke:target seq 481 <<<
GET      eduke (git)
    DELETE      (/home/paul/EmuELEC/sources/eduke/eduke-*/)
    GIT CLONE      eduke
Cloning into '/home/paul/EmuELEC/sources/eduke/eduke-9741acb51c4ba35006ef96cad0d321b94815770f'...
fatal: unable to access 'https://voidpoint.io/terminx/eduke32.git/': server certificate verification failed. CAfile: none CRLfile: none
*********** FAILED COMMAND ***********
. "${get_handler}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/get "${PKG_NAME}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/unpack "${PKG_NAME}" "${PARENT_PKG}"
**************************************
*********** FAILED COMMAND ***********
${SCRIPTS}/build "${1}" "${PARENT_PKG}"
**************************************
FAILURE: scripts/install eduke:target has failed!

The following log for this failure is available:
  /home/paul/EmuELEC/build.EmuELEC-Amlogic-ng.aarch64-4/.threads/logs/481.log

>>> eduke:target seq 481 >>>
[476/525] [FAIL] install eduke:target

```

**Comment by shantigilbert** [comment] 2021-11-04 19:01
Add `export GIT_SSL_NO_VERIFY=1` to the eduke package.mk probably before any function (I forgot to push this change)

**Comment by pjessop** [comment] 2021-11-05 09:50
> Add `export GIT_SSL_NO_VERIFY=1` to the eduke package.mk probably before any function (I forgot to push this change)

That worked perfectly and I made it to the end of the build :)

However, I ran out of disk space as it was making the iso.

How much HD is needed for a full build and compile of EmuELEC?

**Comment by miwasp** [comment] 2021-11-05 13:46
> How much HD is needed for a full build and compile of EmuELEC?

My EmuELEC folder is currently 97gb after a full build of Amlogic-ng. Please be aware that currently a new set of images is created into the target folder every time you start a new build.
If you additionally create images for OGA/OGS and/or Gameforce (not yet possible with this new build system) you will end with additional build… folders, each with 70-90gb.

**Comment by pjessop** [comment] 2021-11-05 15:00
> > How much HD is needed for a full build and compile of EmuELEC?
> 
> My EmuELEC folder is currently 97gb after a full build of Amlogic-ng. Please be aware that currently a new set of images is created into the target folder every time you start a new build. If you additionally create images for OGA/OGS and/or Gameforce (not yet possible with this new build system) you will end with additional build… folders, each with 70-90gb.

Many thanks. I must be agonisingly short of resources.

I'll install Ubuntu on a bigger disk and have another go.

**Closed** 2021-11-05 15:25 UTC
