### ISSUE TITLE
is it possible to add Gpio to your neo emuelec system?

### ISSUE THREAD

**Issue by ctogamez** [EmuELEC/EmuELEC#305] opened 2020-09-30 07:10 UTC
Hello, asakous, all good.

My name is Fabio, and as a player, I use the nickname cto gamez. I am Brazilian and I love oldgen games.

I met this week, your neo emuelec project, and I was very surprised by this system, because it is doing something that I have not seen in other systems, running naomi system very fluidly in many games.
But with USB controls there is always a delay when playing. And I would like to know if it is possible to implement GPIO in your system, as I guarantee that it would be very good.

I thank you for the effort you have made in the scene with orange pi.
and my congratulations, and continue on this beautiful project

Ass: Cto Gamez

**Comment by TheLastProject** [comment] 2020-09-30 07:14
Duplicate of #304 and again wrong repo, this is EmuELEC not Neo EmuELEC. You are probably looking for https://github.com/asakous/Neo-EmuELEC-H3.

**Comment by ctogamez** [comment] 2020-09-30 07:22
thanks (y)

**Closed** 2020-09-30 19:01 UTC
