### ISSUE TITLE
Wifi hotspot name

### ISSUE THREAD

**Issue by alabotski** [EmuELEC/EmuELEC#1111] opened 2023-01-28 08:07 UTC
**Describe the bug**
I have Wi-Fi with name — `¯\_(ツ)_/¯ 5 GHz`
CoreELEC & Android TV work fines with it
Problems only with EmuELEC 4.5 & 4.6
It can't connect

Temporarily I created a hotspot on my phone and EmuELEC without problems connected to it
Apparently there are problems in the name of the Wi-Fi point?
But why does CoreELEC work with it without difficulties?

**Expected behavior**
Set up a connection with my home wifi hotsopt

**EmuELEC version:**
 - Version 4.5
 - Version 4.6

**Device (please complete the following information):**
 - SOC: S095x3
 - Brand: KinHank
 - Model: Super Console X3 Plus

**Comment by Langerz82** [comment] 2023-02-01 05:22
The smiley character isnt part of ASCII, so try removing that and it should work.

**Comment by alabotski** [comment] 2023-02-02 06:58
The rest of the systems work fine, the same CoreElec

**Comment by Langerz82** [comment] 2023-02-03 04:52
The password is saved in a plain text file which does not support other languages and that code is part of Japanese text. You will need to remove it for it to work, this isnt really a bug it's more a feature request.

**Comment by Langerz82** [comment] 2023-04-17 14:43
Closing as not really a bug, but a feature and use discourse forum for features.

**Closed by Langerz82** 2023-04-17 14:43 UTC

**Comment by shantigilbert** [comment] 2023-04-17 21:06
it is not a bug, escape your special chars with a backslash : `$ => \$` `\ => \\` etc you might need to manually edit emuelec.conf
