### ISSUE TITLE
EmuELEC 4.3 1280x800 overscan

### ISSUE THREAD

**Issue by octopusgreen** [EmuELEC/EmuELEC#895] opened 2022-04-14 06:42 UTC
Hi everyone 
my setup specs
device: WeTek Play 2
cpu model: amlogic s905h rev c
EmuELEC version: EmuELEC-Amlogic.aarch64-4.3-Generic.img
monitor: eyoyo 16:10 inch LCD monitor 1280x800
i could tell the image is cut off on the top and not looking right.
i went into the emuelec.conf file and changed the 
## Set video mode ee_videomode=1080p60hz
to
## Set video mode ee_videomode=1280x800p60hz
hoping that would fix the problem but it is still the same overscan screen
any help would be greatly appreciated thank you everyone.

Udate i found a post on
 https://github.com/EmuELEC/EmuELEC/issues/145#issuecomment-602711944
so i launched terminal and put in these lines
fbset -fb /dev/fb0 -g 1280 800 1280 1600 32
        echo 0 0 1279 799 > /sys/class/graphics/fb0/free_scale_axis
        echo 45 25 1235 775 > /sys/class/graphics/fb0/window_axis
        echo 0x10001 > /sys/class/graphics/fb0/free_scale
and after i put in them lines the overscan is gone in the terminal the screen is perfect.
but when i exit the terminal the overscan comes back.
i do not know how to save the settings to keep the changes.
the post has 4 steps i can only understand 2 out of 4.

**Comment by shantigilbert** [comment] 2022-04-17 18:27
This is a duplicate of #61 #145 please refer to those issues

**Closed by shantigilbert** 2022-04-17 18:27 UTC
