### ISSUE TITLE
Weird bug where the screen is black on launching a game

### ISSUE THREAD

**Issue by Cee123** [EmuELEC/EmuELEC#614] opened 2021-05-18 02:17 UTC
**Describe the bug**
I'm getting this weird issue where, whenever I launch a game on EmuElec (Odroid Go Advance), it goes black but the sound is still playing and I have to enter to Retroarch menu and then exit it again for the game to appear.

**To Reproduce**
I'm not sure how to reproduce this. Just wondering if anyone else has the same issue.

**Expected behavior**
The game should just display, however, it doesn't. You have to access the retroarch menu first.

**Screenshots**

**EmuELEC version:**
4.x (tried 4.1 and 4.2) test versions

**Device (please complete the following information) and make sure its a [SUPPORTED DEVICE](https://github.com/EmuELEC/EmuELEC/wiki/Supported-Devices) **
Odroid Go Advance

**Additional context**
I updated using the tar.gz file, instead of a complete reflash of the SD card. I really didn't want to go through all of the copying stuff over etc again as last time it took over an hour. I've also tried restoring all the default configs and binaries under the EmuElec menu. I've also tried that vulkan fix mentioned in the latest release notes.

**Comment by shantigilbert** [comment] 2021-05-22 19:16
I no longer have a OGA v1.0 so I cannot test this, but on all the other RK3326 devices I have with EmuELEC I cannot reproduce.

**Comment by Cee123** [comment] 2021-05-23 02:05
> I no longer have a OGA v1.0 so I cannot test this, but on all the other RK3326 devices I have with EmuELEC I cannot reproduce.

Oh ok, no worries. It could be something simple to do with retroarch maybe. I'll try different settings see if I can fix it.

**Comment by shantigilbert** [comment] 2021-05-23 17:02
Let me know if you find a way to reproduce this

**Comment by shantigilbert** [comment] 2021-05-31 05:31
No info for 8 days, closing

**Closed by shantigilbert** 2021-05-31 05:31 UTC

**Comment by Cee123** [comment] 2021-07-09 02:34
@shantigilbert I just managed to fix this issue today. It was simple a fix as changing the video driver from gl to glcore.
