### ISSUE TITLE
Image flickers

### ISSUE THREAD

**Issue by b0b33140** [EmuELEC/EmuELEC#216] opened 2020-07-05 07:19 UTC
**Describe the bug**
My screen constantly flickers for about 2s.

**EmuELEC version:**
EMUELEC 3.6 NG

**Device (please complete the following information):**
 - SOC: S905x2
 - Brand: Beelink
 - Model GT1 mini 4G
 - Version 95X2

**Comment by ws02589111** [comment] 2020-07-09 10:36
I get the same problem, but the flashing frequency faster than 2s

EmuELEC version:
EMUELEC 3.6

Device:

SOC: S905M2
Brand: Q5
Model: None
Version: None

**Comment by shantigilbert** [comment] 2020-07-09 18:11
Does it work when using CoreELEC? or regular Android?  this does not seem related to EmuELEC at all, I have a GT1 mini 4G and I can assure you, I do not get any flickering.

**Comment by b0b33140** [comment] 2020-07-10 15:00
Je n'ai pas ce problème sous Android.
Je vais esayer de remètre la version antérieur (3.5).

**Comment by b0b33140** [comment] 2020-07-12 06:17
Version 3.5 does not have this problem.
I think this problem may not be visible depending on the screen used.

**Comment by kyo750904** [comment] 2020-07-17 05:31
My device also flashes
GT KING S922X

**Comment by shantigilbert** [comment] 2020-11-26 17:14
I cannot reproduce this, sorry.  I will close this issue but feel free to reopen with more information if this issue is still present in newer versions.

**Closed by shantigilbert** 2020-11-26 17:14 UTC
