### ISSUE TITLE
Controller config mapping is not work in xmb menu driver

### ISSUE THREAD

**Issue by ws02589111** [EmuELEC/EmuELEC#556] opened 2021-04-11 04:25 UTC
**Describe the bug**
Because of using ozone with CN has garble, I‘m set the retroarch menu to xmb， and set the file `packages/sx05re/emuelec/bin/setsettings.sh ` line 597 to xmb( #545).

And then, I configure my controller in ES front. In  ES front the controller is work fine, but in RetroArch, the controller can't work properly.
I have check the retroarch.cfg. in xmb, the values about input_player1_* is all nul, but in ozone, the values is what i configured in ES front

**To Reproduce**
1. Set your menu driver to xmb
2. Go to ES front to configure your controller
3. Check  your setting in RetroArch input setting

**Expected behavior**
Controller setting can mapping to retroarch 

**Screenshots**
1.Configure in XMB
![image](https://user-images.githubusercontent.com/10301545/114292255-c0435000-9abf-11eb-9085-0cb6f29ca104.png)
2.Configure in OZONE
![image](https://user-images.githubusercontent.com/10301545/114292258-d224f300-9abf-11eb-94db-8f53d9c77349.png)

**EmuELEC version:**
 - Version: dev branch commit: #54c55f5b7e74e0973e05dad79dde1cc7df5346c1

**Device
 - SOC: S905M

**Comment by shantigilbert** [comment] 2021-04-11 17:23
retroarch.cfg does not handle gamepads, the menu driver should not care what your gamepad is. Configure your gamepad in ES and it should be configured in Retroarch as well, do not modify files manually! 

Alternative configure your controller in the RA menu. 

Again, since this is not a bug, but a user error, please use discord for this. 

Closing this issue.

**Closed by shantigilbert** 2021-04-11 17:23 UTC
